// alert message text
let alertConfig = {
  alertFail: 'Fail',
  alertSuccess: 'Success',
  serviceCurrentlyUnavailable: 'Service currently unavailable',
  userNotFound: 'User not found',
  userAlreadyExists: 'User Already Exists',
  passwordIncorrect: 'Password Incorrect',
  pleaseEnterUserName: 'Please enter user name',
  loginSuccessfully: 'You are Log in Successfully',
  logoutSuccessfully: 'You are Log out Successfully',
  signupSuccessfully: 'You are registered Successfully',
  imageUploadSuccessfully: 'image uploaded to firebase',
  imageCannotRecognize: 'Image can not recognize',
  journalLogCreated: 'Journal log created',
  logOutConfirmation: 'Are you sure you want to logout?',
  iconUploadSuccessfully: 'Icon uploaded successfully!',
  alreadyLogin: 'Already log in!',
  baiduApiError: 'Something wrong with Baidu Api',
  googleVisionApiError: 'Something wrong with Google Vision Api',
  flickrApiError: 'Something wrong with flickr Api',
  selectFromLocalFSFail: 'Can not select from Local file',
  baiduTranslateApiError: 'Something wrong with Baidu Translate Api',
  noMatchResult: 'Please do a image classification first',
  imageCompression: 'Image unable to compress',
  readFileFail: 'Can not read file',
  logPreviewImageDelete: 'Are you sure to delete?',
  logSubmitSuccessfully: 'Log submitted successfully',
  ok: 'Ok',
  include: 'Include',
  okAndGoToCamera: 'Ok and Go to Camera',
  LogSuccessfullySubmit: 'Journal Log successfully submit',
  deleteJournalLog: 'Sure to delete the Journal?',
  deleteUser: 'Sure to delete user?',
  deleteImage: 'Sure to delete Image?',
  voteConfirm: 'Sure to submit votes?',
  forumConfirm: 'Sure to submit forum?',
  journalSubmitConfirm: 'Sure to submit journal?',
  geolocationServiceUnavailable: 'Geolocation Service currently unavailable',
  geolocationPermissionDeny: 'Geolocation permission deny',
  fromMarkerToDiscover: 'Sure to navigate to Discover Page?',
  journalSubmitGeoConfirm: 'Sure to include location info?',
  expertJudgementSubmitGeoConfirm: 'Sure to submit expert judgement?',
  inValidImageFormat: 'Only support image format jpg and png',
  fromDiscoverToMap: 'Sure to navigate to Map Page?',
  fromDiscoverToImageClassification:
    'Sure to navigate to Image Classification Page?',
  cancel: 'Cancel',
  no: 'No',
  alertConfirm: 'Confirm',
};
export default alertConfig;
